apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-cluster-network-policies
  namespace: flux-system
spec:
  # The interval at which to reconcile the Helm release
  interval: 10m
  releaseName: default-cluster-network-policies
  targetNamespace: kube-system
  chart:
    spec:
      # The path of the chart relative to the repository root
      chart: ./security/default-cluster-network-policies
      version: '0.1.0'
      # The reference to the GitRepository
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: default-cluster-values