apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-namespace-network-policies-default
  namespace: flux-system
spec:
  # The interval at which to reconcile the Helm release
  interval: 10m
  releaseName: default-namespace-network-policies
  targetNamespace: default
  chart:
    spec:
      # The path of the chart relative to the repository root
      chart: ./security/default-namespace-network-policies
      version: '0.1.0'
      # The reference to the GitRepository
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: flux-system
      valuesFrom:
      - kind: ConfigMap
        name: default-cluster-values
      values:
        allow_namespace_traffic: false
        allow_ingress_cluster_traffic: false
        allow_egress_cluster_traffic: false
        allow_ingress_private_traffic: false
        allow_egress_private_traffic: false
        allow_monitoring: false
        allow_apiserver: false
        allow_internet: false
        allow_ingress_traffic: false
        allow_egress_traffic: false