apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: default-cluster-network-policies
  namespace: flux   # we put HelmRelease resources into flux namespace to make use of secretRef with Git credentials
spec:
  releaseName: default-cluster-network-policies
  targetNamespace: kube-system   # the namespace where Helm chart gets deployed
  chart:
    git: "https://bitbucket.org/example/helm"
    path: "security/default-cluster-network-policies"
    version: "0.1.0"
    secretRef:
      name: flux-git-auth
  valuesFrom:
  - configMapKeyRef:
      name: default-cluster-values
