---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azuredevops
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azuredevops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: azuredevops
  namespace: kube-system

## The RoleBinding below is required to modify ServiceMonitor objects from Prometheus Operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azuredevops-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-prometheus-oper-operator
subjects:
- kind: ServiceAccount
  name: azuredevops
  namespace: kube-system

## Allow PodPreset object modifications
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podpreset-reader
rules:
- apiGroups: ["settings.k8s.io"]
  resources: ["podpresets"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azuredevops-podpreset-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podpreset-reader
subjects:
- kind: ServiceAccount
  name: azuredevops
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedcertificates-role
rules:
  - apiGroups: ["networking.gke.io"]
    resources: ["managedcertificates"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azuredevops-managedcertificates-admin
subjects:
  - kind: ServiceAccount
    name: azuredevops
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: managedcertificates-role
  apiGroup: rbac.authorization.k8s.io
