apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      release: prometheus
    name: flux
    namespace: flux
  spec:
    endpoints:
    - honorLabels: true
      port: http
    namespaceSelector:
      matchNames:
      - flux
    selector:
      matchLabels:
        app: flux
        release: flux
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      release: prometheus
    name: helm-operator
    namespace: flux
  spec:
    endpoints:
    - honorLabels: true
      port: http
    namespaceSelector:
      matchNames:
      - flux
    selector:
      matchLabels:
        app: helm-operator
        release: helm-operator
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
